Repository Dude-Perfect-Discord-Bot/Dude-Perfect, pull requests merged in 2020-12, with the labels that each got.

#39 feat(Listener): missingPermissions listener and command updates
  src/commands/Server Management/createChannel.js
  src/commands/Server Management/deleteChannel.js
  src/commands/Server Management/nickname.js
  src/commands/Server Management/purge.js
  src/commands/Server Management/slowmode.js
  src/commands/Server Management/voiceKick.js
  src/listeners/commandHandler/missingPermission.js
Labels: Meta: Feature, Priority: Medium, Type: Enhancement

#51 Fixed Grammatical erorr and shortened code
  src/commands/Fun/viewPerms.js
Labels: Meta: Typings, Type: Typo

#54 Made a reload Command
  src/commands/Owner Only/reload.js
Labels: Meta: Feature, SEM: Minor, Type: Enhancement
