Repository Dude-Perfect-Discord-Bot/Dude-Perfect, pull requests merged in 2021-06, with the labels that each got.

#107 chore: update Top.gg dependency
  package.json
  src/index.js
  src/listeners/dbl/error.js
  yarn.lock
Labels: Meta: Dependencies, Type: Dependencies

#121 feat: cleanup code and improvements
  .github/workflows/lint.yml
  package.json
  pnpm-lock.yaml
  src/commands/Fun/8ball.js
  src/commands/Fun/advice.js
  src/commands/Fun/cat.js
  src/commands/Fun/dog.js
  src/commands/Fun/figlet.js
  src/commands/Fun/meme.js
  src/commands/Fun/viewPerms.js
  src/commands/Fun/wouldYouRather.js
  src/commands/Information/avatar.js
  src/commands/Information/enlarge.js
  src/commands/Information/guild.js
  src/commands/Information/info.js
  src/commands/Information/viewPerms.js
  src/commands/Owner Only/eval.js
  src/commands/Owner Only/reload.js
  src/commands/Owner/eval.js
  src/commands/Owner/reload.js
  src/commands/Server Management/createChannel.js
  src/commands/Server Management/deleteChannel.js
  src/commands/Server Management/nickname.js
  src/commands/Server Management/purge.js
  src/commands/Server Management/slowmode.js
  src/commands/Server Management/voiceKick.js
  src/commands/Utilities/about.js
  src/commands/Utilities/help.js
  src/commands/Utilities/invite.js
  src/commands/Utilities/ping.js
  src/commands/Utilities/support.js
  src/commands/Utilities/uptime.js
  src/index.js
  src/listeners/commandHandler/commandStart.js
  src/listeners/commandHandler/missingPermission.js
  src/listeners/dbl/error.js
  src/listeners/ready.js
  src/listeners/statcord/autopost.js
  src/listeners/statcord/clientReady.js
  src/listeners/statcord/post.js
  src/models/.gitkeep
  src/utility/.gitkeep
  src/utility/formatDuration.js
  src/utility/normalizePermFlag.js
  yarn-error.log
  yarn.lock
Labels: Meta: Cleanup, Status: Review Ready

#123 fix(avatar): remove auto delete of output
  package.json
  src/commands/Information/avatar.js
Labels: Meta: BugFix, SEM: Minor

#125 feat(userinfo): Adds nitro badge to userinfo
  src/commands/Information/info.js
  src/extensions/DudePerfectUser.js
  src/index.js
Labels: Meta: Feature, Type: Enhancement

#128 fix(Intelliji): remove config
  .idea/.gitignore
  .idea/Alpha Dude Perfect.iml
  .idea/discord.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: Meta: BugFix, Meta: Error Handling, SEM: Patch, Type: Performance
